// todo-angular/src/app/components/kanban-column/kanban-column.ts
import { Component, inject, input, output } from '@angular/core';
import { ADD } from '../../util/icons';
import { TaskCard } from '../task-card/task-card';
import { TaskService } from '../../services/tasks/task.service';

@Component({
  selector: 'app-kanban-column',
  imports: [TaskCard],
  template: `
    <div
      class="sticky flex items-center justify-between bg-background rounded-t-lg p-4 border-b border-border"
    >
      <div class="flex items-center space-x-2">
        <h2 class="font-semibold text-foreground">{{ title() }}</h2>
        <span class="bg-muted text-muted-foreground text-xs px-2 py-1 rounded-full">
          {{ tasks()?.length || 0 }}
        </span>
      </div>
      @if (onAddClick) {
        <button
          (click)="onAddClick.emit(title())"
          class="text-foreground/40 hover:text-foreground/50 cursor-pointer"
        >
          {{ ADD }}
        </button>
      }
    </div>

    <div
      class="grow p-4 space-y-3"
      (dragover)="onDragOver($event)"
      (drop)="onDragDrop($event, title())"
    >
      @for (task of tasks(); track task.Id) {
        <div draggable="true" (dragstart)="onDragStart($event, task.Id!)">
          <app-task-card [task]="task" />
        </div>
      }

      @if (!tasks()?.length) {
        <div class="text-center py-16 text-muted-foreground">
          <p class="text-sm">No tasks yet</p>
          <button
            (click)="onAddClick.emit(title())"
            class="text-primary hover:text-primary-dark text-sm mt-1"
          >
            Add your first task
          </button>
        </div>
      }
    </div>
  `,
  styles: ``,
})
export class KanbanColumn {
  taskService = inject(TaskService)
  tasks = input<Task[]>();
  title = input.required<string>();
  ADD = ADD;
  onAddClick = output<string>();

  onDragStart = (event: Event, taskId: string) => {
    const e = event as DragEvent;
    e.dataTransfer?.setData('text/plain', taskId);
  };

  onDragOver = (e: Event) => {
    e.preventDefault();
  };

  onDragDrop = async(event: Event, targetStatus: string) => {
    event.preventDefault();

    const e = event as DragEvent;
    const taskId = e.dataTransfer?.getData('text/plain');
    if(taskId)
     await this.taskService.changeStatus(taskId, targetStatus)
  };
}

// todo-react/src/components/KanbanColumn.tsx
import React from "react";
import TaskCard from "./task/TaskCard";
import { ADD } from "../util/icons";
import { sortDsc as sortDesc } from "../util/converter";

interface KanbanColumnProps {
  title: string;
  tasks: Task[];
  onNewTask: () => void;
  onEditTask: (task: Task) => void;
  onDrop: (e: React.DragEvent) => void;
  onDragOver: (e: React.DragEvent) => void;
  onDragStart: (e: React.DragEvent, task: Task) => void;
  allowCreation?: boolean;
}

const KanbanColumn: React.FC<KanbanColumnProps> = ({
  title,
  tasks,
  allowCreation = true,
  onNewTask,
  onEditTask,
  onDrop,
  onDragOver,
  onDragStart,
}) => {
  return (
    <div className="flex flex-col h-fit shrink-0 w-80 rounded-lg border border-border">
      <div className="sticky flex items-center justify-between bg-secondary rounded-t-lg p-4 border-b border-border">
        <div className="flex items-center space-x-2">
          <h2 className="font-semibold text-foreground">{title}</h2>
          <span className="bg-secondary-dark text-muted-foreground text-xs px-2 py-1 rounded-full">
            {tasks.length}
          </span>
        </div>
        {allowCreation && (
          <button
            onClick={onNewTask}
            className="text-muted-foreground hover:text-foreground cursor-pointer"
          >
            {ADD}
          </button>
        )}
      </div>

      <div
        className="grow p-4 space-y-3"
        onDrop={onDrop}
        onDragOver={onDragOver}
      >
        {tasks.sort(sortDesc).map((task) => (
          <div
            key={task.Id}
            draggable
            onDragStart={(e) => onDragStart(e, task)}
          >
            <TaskCard task={task} onEdit={onEditTask} />
          </div>
        ))}

        {tasks.length === 0 && (
          <div className="text-center py-8 text-muted-foreground">
            <p className="text-sm">No tasks yet</p>
            <button
              onClick={onNewTask}
              className="text-primary hover:text-primary-dark text-sm mt-1"
            >
              Add your first task
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

export default KanbanColumn;
